### ISSUE TITLE
Suggestion to support Chinese directory path

### ISSUE THREAD

**Issue by xyliaaaaa** [ryjfgjl/python-excelimporter#1]
Thank you very much for your sharing! It helps a lot. 
I have some tiny advice here.
In file ‘excelimporter.py’, Pandas's read_csv(file_name) funcion does not support Chinese directory path with the default parser engine. So I suggest to set the parameter 'engine' to 'python'.
Like this:
`dataset = pd.read_csv(csv, encoding=encode, dtype=str, keep_default_na=False, engine='python')` will work well.

**Comment by ryjfgjl** [comment]
I'm really appreciate thay you advised me this.
I will fix it soon after.

Best.

**Comment by ryjfgjl** [comment]
> Pandas's read_csv(file_name) funcion does not support Chinese directory path with the default parser engine

Hi @xyliaaaaa ,

**Comment by ryjfgjl** [comment]
> Thank you very much for your sharing! It helps a lot.
> I have some tiny advice here.
> In file ‘excelimporter.py’, Pandas's read_csv(file_name) funcion does not support Chinese directory path with the default parser engine. So I suggest to set the parameter 'engine' to 'python'.
> Like this:
> `dataset = pd.read_csv(csv, encoding=encode, dtype=str, keep_default_na=False, engine='python')` will work well.

Hi @xyliaaaaa ,
This is not a problem for me.
The version of my python is 3.7 and pandas is 0.25. 
I guess the version caused this issue. 
See https://github.com/pandas-dev/pandas/issues/17188.
It is maybe fixed in my version.
But I'm not sure and forgive me that I only can try my best to support/test it based on the latest python/pandas version.

Thanks again for your professional suggestion.
